version: '3'

services:
  node_demo:
    image: harbornode.mydadao.com/test/node_demo:1.0
    environment:
     NODE_ENV: "dev"
    ports:
      - "3000:3000"

    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
    networks:
      - swarm_network

networks:
  swarm_network:
    external:
      name: hill
